### ISSUE TITLE
ao build: error: Uncaught (in promise) NotFound: program not found

### ISSUE THREAD

**Issue by xgocn** [permaweb/aos#362]
I ran `ao build` with Git bash in windows11，and got this error
```
Administrator@10_3_0_14 MINGW64 /c/aos/process (main)
$ ao build
error: Uncaught (in promise) NotFound: program not found
    at opRun (ext:runtime/40_process.js:58:10)
    at Object.run (ext:runtime/40_process.js:155:15)
    at Command.build [as actionHandler] (file:///C:/Users/ADMINI~1/AppData/Local/Temp/2/deno-compile-ao.exe/dev-cli/src/commands/build.js:8:18)
    at Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:770:18)
    at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:652:14)
    at async file:///C:/Users/ADMINI~1/AppData/Local/Temp/2/deno-compile-ao.exe/dev-cli/src/mod.js:30:1
```

ao was installed:
```
$ ao --help

Usage:   ao
Version: 0.1.5

Description:

  The ao CLI for build, publishing, and spawning ao Modules and Processes

Options:

  -h, --help     - Show this help.
  -V, --version  - Show the version number for this program.

Commands:

  init     <name>      - Create an ao Process Source Project
  lua                  - Start a Lua Repl
  run      <file>      - Run a Lua File
  build                - Build the Lua Project into WASM
  publish  <wasmfile>  - Publish the file to Arweave
  spawn                - Spawn an ao Process using a published ao Module
  bundler              - ao CLI Bundler commands
  exec     <command>   - Exec command in the container ( ie: exec emcmake cmake . )
```

How can I fix it?

**Comment by xgocn** [comment]
I found that the entire `C:\Users\Administrator\AppData\Local\Temp\2\deno-compile-ao.exe\` folder is empty except for directory an empty `node_modules` inside
