### ISSUE TITLE
AOS Crash on unexpected non-string return value

### ISSUE THREAD

**Issue by nikooo777** [permaweb/aos#400]
Reproduction:

start a process, with the `.editor` set this code:
```lua
function ReturnTrueTable()
    return true, {a = "b"}
end
```
`.done`

call the function:
```lua
ReturnTrueTable()
```

observe the crash:

```bash
file:///home/niko/.nvm/versions/node/v20.15.0/lib/node_modules/@permaweb/aos/src/services/errors.js:22
  const errorMessage = error.replace(
                             ^

TypeError: error.replace is not a function
    at parseError (file:///home/niko/.nvm/versions/node/v20.15.0/lib/node_modules/@permaweb/aos/src/services/errors.js:22:30)
    at doEvaluate (file:///home/niko/.nvm/versions/node/v20.15.0/lib/node_modules/@permaweb/aos/src/index.js:533:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Interface.<anonymous> (file:///home/niko/.nvm/versions/node/v20.15.0/lib/node_modules/@permaweb/aos/src/index.js:415:9)

Node.js v20.15.0
```

Further information:

whenever a function returns two values, ao considers second argument an error message and tries to parse it:

```lua
result == {
  Messages: [],
  Assignments: [],
  Spawns: [],
  Output: '',
  GasUsed: 0,
  Error: { a: 'b' }
}
```

the quickest workaround is to return a single value.

**Comment by nikooo777** [comment]
we accidentally sent in the same issue twice. #399

**Comment by jfrain99** [comment]
Hello @nikooo777, thank you for the issue! After some digging, it's been determined that this is a result of the AO Loader handling multiple returns as an error. We hope to fix this in the Loader, but in the meantime, it is suggested to wrap the return values in a Lua Table/TableArray to avoid this issue.
